# Generated by Django 6.1.1 on 2026-09-04 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('title', models.CharField(max_length=80)),
                ('content', models.CharField(blank=True, default='', max_length=200)),
                ('priority', models.IntegerField(choices=[(2, '낮음'), (3, '보통'), (5, '긴급')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='zones.zone')),
            ],
            options={
                'ordering': ['event_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='알림 시점 코드. "D-1 20:00" 처럼 일 오프셋과 정각 시각으로 적는다.', max_length=16)),
                ('due_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('fail_count', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=200)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='notices.notice')),
            ],
            options={
                'ordering': ['due_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['zone', 'event_date'], name='notices_not_zone_id_6ab8c1_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['sent_at', 'due_at'], name='notices_ale_sent_at_1867fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(fields=('notice', 'code'), name='uniq_alert_code_per_notice'),
        ),
    ]
