# Generated by Django 6.1.1 on 2026-09-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='완료 표시한 시각. 완료하면 목록·달력 점에서 빠지고 남은 알림도 나가지 않는다.', null=True),
        ),
    ]
