# Generated by Django 6.1.1 on 2026-09-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_notice_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
