# Generated by Django 6.1.1 on 2026-09-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_alert_is_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='fail_count',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='is_pending',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='last_error',
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(blank=True, choices=[('', '예약'), ('sent', '발송됨'), ('fail', '발송 실패')], default='', max_length=4),
        ),
    ]
