# Generated by Django 6.1.1 on 2026-09-08 01:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_alter_notice_options_notice_event_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='event_hour',
            field=models.PositiveSmallIntegerField(blank=True, help_text="몇 시 일인지. 비워두면 시각을 정하지 않은 것으로 본다 분은 받지 않는다 — 어린이집 준비물처럼 '오전 중' 이면 되는 일이 대부분이라 분까지 물으면 없는 정확도를 지어내게 된다.", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
    ]
