# Generated by Django 6.1.1 on 2026-09-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0009_rename_notice_to_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='held_at',
            field=models.DateTimeField(blank=True, help_text="보류한 시각. 취소됐지만 다시 잡힐 수 있는 일정을 지우는 대신 여기로 치운다 — 지우면 제목·내용·알림 시점을 다음에 처음부터 다시 적어야 한다. 보류하면 날짜를 축으로 삼는 모든 화면(목록·달력·주간 정리)과 발송에서 빠지고 보류함(?filter=held)에만 남는다. event_date 는 마지막으로 잡혔던 날 그대로 두는데, 보류함이 '9월 14일에 있던 일정' 이라고 적어줘야 무엇을 미룬 것인지 알아볼 수 있어서다.", null=True),
        ),
    ]
