# Generated by Django 6.1.1 on 2026-09-15 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0010_event_held_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='priority',
        ),
    ]
