# Generated by Django 6.1.1 on 2026-09-17 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0011_remove_event_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.CharField(choices=[('daily', '매일'), ('weekly', '매주'), ('monthly', '매월'), ('yearly', '매년')], max_length=8)),
                ('weekdays', models.CharField(blank=True, default='', help_text='매주일 때 요일들. 월=0 … 일=6 을 쉼표로 ("0,2,4"). 다른 규칙은 비운다.', max_length=13)),
                ('until', models.DateField(help_text='마지막으로 반복할 수 있는 날 (포함)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='series',
            field=models.ForeignKey(blank=True, help_text="반복으로 만든 일정이면 그 규칙. '이후 모두 고치기·지우기' 가 이것으로 형제를 찾는다.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='notices.eventseries'),
        ),
    ]
