# Generated by Django 6.1.1 on 2026-09-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0012_event_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='canceled_at',
            field=models.DateTimeField(blank=True, help_text="취소한 시각. **날짜에 그대로 남는다** — 완료와 같은 자리에 흐리게, 취소선을 긋고 남는다. 지우지 않는 까닭이 이것이다: 몇 주 뒤에 달력을 보다가 '이 날 뭐가 있었는데 뭐였지' 하는 순간, 지워버렸으면 답할 길이 없고 남아 있으면 '아, 취소했지' 로 끝난다. 보류와 갈리는 지점이기도 하다 — 보류는 다시 잡을 일이라 날짜를 떠나 보류함으로 가고, 취소는 다시 잡지 않을 일이라 그 날에 눌러앉는다.", null=True),
        ),
    ]
