# Generated by Django 6.1.1 on 2026-09-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0013_event_canceled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='starred_at',
            field=models.DateTimeField(blank=True, help_text='즐겨찾기에 넣은 시각. 등록 폼이 제목 칸 아래에 내놓는 목록이 이것이다 — 고르면 제목·내용·공간·시각·알림 시점이 한 번에 채워지고 날짜만 빈다.\n\n**쓴 횟수로 세지 않고 사람이 정한다.** 예전에는 지난 기록에서 자주 쓴 것을 뽑아 줬는데, 많이 적은 것과 다시 쓰고 싶은 것은 같지 않았다 — 병원은 자주 갔지만 다시 적을 일은 아니고, 1년에 두 번인 학부모 상담은 매번 그대로 다시 적는다.\n\n시각을 남기는 것은 최근에 넣은 것이 위에 서게 하려는 것이다(불리언이면 줄 세울 것이 없다). 완료·취소·보류가 모두 같은 방식이다.', null=True),
        ),
    ]
