# Generated by Django 6.1.1 on 2026-10-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0014_event_starred_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseries',
            name='lunar',
            field=models.BooleanField(default=False, help_text='매년일 때 음력 날짜로 되풀이한다(부모님 생신처럼). 다른 규칙은 늘 거짓.'),
        ),
    ]
