# Generated by Django 6.1.1 on 2026-10-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0017_series_template_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text="완료 표시한 시각. 완료하면 목록·달력에서 빠지고 남은 알림도 나가지 않는다. **뒤로 잡은 알림(D+n)은 그대로 나간다** — '교체한 지 200일 뒤' 는 끝낸 뒤에 올 알림이라, 완료했다고 멈추면 잡아둔 뜻이 없다(`views.due_alerts`).", null=True),
        ),
    ]
