# Generated by Django 6.1.1 on 2026-09-15 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('refresh_token', models.CharField(max_length=512)),
                ('access_token', models.CharField(blank=True, default='', max_length=2048)),
                ('access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('calendar_id', models.CharField(blank=True, default='', max_length=255)),
                ('broken_at', models.DateTimeField(blank=True, help_text="구글이 열쇠를 거절한 때. 사람이 구글 계정에서 권한을 거뒀거나 비밀번호를 바꿨을 때다. 줄을 지우지 않는 것은 설정 화면이 '끊겼어요, 다시 연결하세요' 를 말해야 해서다 — 지우면 연결한 적 없는 것과 구별되지 않는다.", null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
