# Generated by Django 6.1.1 on 2026-09-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text="처음 받은 비밀번호(0000)를 아직 안 바꿨다. 켜져 있으면 내 정보 조회와 비밀번호 변경 말고는 API 가 전부 403 으로 막힌다(`accounts.authentication`). 화면의 '사용자 추가' 로 만든 계정만 켜진다 — createsuperuser 나 관리자 사이트로 만든 계정은 비밀번호를 직접 정했으므로 끈 채로 둔다."),
        ),
    ]
