# Generated by Django 6.1.1 on 2026-09-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='"user:hoon" · "ip:1.2.3.4"', max_length=190, unique=True)),
                ('failures', models.PositiveSmallIntegerField(default=0)),
                ('first_failed_at', models.DateTimeField()),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['locked_until'], name='accounts_lo_locked__87543f_idx')],
            },
        ),
    ]
