# Generated by Django 6.1.1 on 2026-09-04 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                # 토픽은 이후 User 로 옮겨갔다. 생성 함수가 사라졌으므로 참조를 끊어둔다
                ('ntfy_topic', models.CharField(default='', max_length=64, unique=True)),
                ('last_polled_at', models.DateTimeField(blank=True, help_text='n8n이 /alerts/due 를 마지막으로 조회한 시각', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='uniq_zone_name_per_owner')],
            },
        ),
    ]
