# Generated by Django 6.1.1 on 2026-09-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='color',
            field=models.CharField(blank=True, help_text='칩·카드 막대에 쓰는 색. 비워두면 팔레트에서 자동 배정된다.', max_length=7),
        ),
    ]
