# Generated by Django 6.1.1 on 2026-09-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0006_palette_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='last_polled_at',
        ),
        migrations.AlterField(
            model_name='zone',
            name='ntfy_topic',
            field=models.CharField(blank=True, help_text='알림을 받을 토픽. 비워두면 추측하기 어려운 값을 자동으로 만든다.', max_length=64, unique=True),
        ),
    ]
