# Generated by Django 6.1.1 on 2026-09-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0007_remove_zone_last_polled_at_alter_zone_ntfy_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='ntfy_topic',
            field=models.CharField(blank=True, default='alrimi-알리미', help_text='알림을 받을 토픽. 비워두면 추측하기 어려운 값을 자동으로 만든다.', max_length=64),
        ),
    ]
