# Generated by Django 6.1.1 on 2026-09-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0008_alter_zone_ntfy_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='ntfy_topic',
        ),
    ]
