# Generated by Django 6.1.1 on 2026-09-17 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def carry_over(apps, schema_editor):
    """
    공간마다 적어두던 구성원을 사람마다의 공유로 옮긴다. 구성원이 있던 공간은 함께 보기를
    켜둔다 — 옮긴 뒤에도 그 사람들이 보던 것이 그대로 보이게.

    주인의 다른 공유 공간도 그 사람들에게 보이게 되지만, 이전 구조에서는 공유 공간이
    드물었고(방금 생긴 기능이다) 공간마다 사람을 가르는 길은 이제 없다.
    """
    ZoneMember = apps.get_model("zones", "ZoneMember")
    Sharing = apps.get_model("zones", "Sharing")
    Zone = apps.get_model("zones", "Zone")

    pairs = set()
    shared_zones = set()
    for member in ZoneMember.objects.select_related("zone"):
        if member.user_id != member.zone.owner_id:
            pairs.add((member.zone.owner_id, member.user_id))
        shared_zones.add(member.zone_id)

    Sharing.objects.bulk_create(Sharing(owner_id=o, viewer_id=v) for o, v in pairs)
    Zone.objects.filter(id__in=shared_zones).update(shared=True)


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0010_zone_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='zone',
            name='shared',
            field=models.BooleanField(default=False, help_text="함께 보기. 켜면 주인이 정해둔 '함께 보는 사람'(`Sharing`) 모두가 이 공간의 일정을 보고 알림을 받는다. 사람은 주인마다 한 번 정하고, 공간은 켜고 끄기만 한다."),
        ),
        migrations.AddField(
            model_name='sharing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharing',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(carry_over, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='zonemember',
            name='uniq_zone_member',
        ),
        migrations.RemoveField(
            model_name='zonemember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='zonemember',
            name='zone',
        ),
        migrations.AddConstraint(
            model_name='sharing',
            constraint=models.UniqueConstraint(fields=('owner', 'viewer'), name='uniq_sharing'),
        ),
        migrations.AddConstraint(
            model_name='sharing',
            constraint=models.CheckConstraint(condition=models.Q(('owner', models.F('viewer')), _negated=True), name='sharing_not_self'),
        ),
        migrations.DeleteModel(
            name='ZoneMember',
        ),
    ]
