# Generated by Django 6.1.1 on 2026-09-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0011_sharing_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='viewers_can_edit',
            field=models.BooleanField(default=False, help_text='함께 보는 사람도 이 공간의 일정을 추가·수정·완료·삭제할 수 있다. 함께 보기가 켜져 있을 때만 뜻이 있다. 공간 이름·색·함께 보기 설정은 여전히 주인만 바꾼다.'),
        ),
    ]
