# Generated by Django 6.1.1 on 2026-09-14 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='이 표시가 찍히는 날')),
                ('kind', models.CharField(choices=[('holiday', '공휴일'), ('term', '절기'), ('memorial', '기념일')], help_text='공휴일·절기·기념일', max_length=16)),
                ('name', models.CharField(help_text='달력에 적히는 이름. "설날" · "추분"', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'kind'],
                'indexes': [models.Index(fields=['date'], name='special_day_date_11a56d_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'kind'), name='uniq_special_day_per_kind')],
            },
        ),
        migrations.CreateModel(
            name='MarkStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('holiday', '공휴일'), ('term', '절기'), ('memorial', '기념일')], max_length=16)),
                ('color', models.CharField(help_text='팔레트 안의 값만 (`palette.py`)', max_length=7)),
                ('shown', models.BooleanField(default=True, help_text='끄면 달력·목록 어디에도 안 나온다')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_styles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind'],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind'), name='uniq_mark_style_per_kind')],
            },
        ),
    ]
