# Generated by Django 6.1.1 on 2026-09-14 16:42

from django.db import migrations, models

#  더 이상 담지 않는 종류. 쉬지 않는 기념일(식목일·스승의날)은 한 해에 수십 개인데
#  달력이 이름으로 덮이기만 하고 대부분은 찾지 않아서 뺐다.
GONE = "memorial"


def drop_memorial(apps, _schema_editor):
    """
    남겨두면 유령이 된다 — `GET /special-days` 는 계속 내려주는데 웹에는 그 종류의
    색이 없어 아무 데도 안 그려진다. 다음에 자료를 들여다보는 사람만 헷갈린다.
    """
    apps.get_model("special_days", "SpecialDay").objects.filter(kind=GONE).delete()
    apps.get_model("special_days", "MarkStyle").objects.filter(kind=GONE).delete()


def keep_nothing(_apps, _schema_editor):
    """되돌릴 것이 없다. 지운 기념일은 다음 동기화가 다시 넣어줄 자료다."""


class Migration(migrations.Migration):

    dependencies = [
        ('special_days', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(drop_memorial, keep_nothing),
        migrations.RemoveField(
            model_name='markstyle',
            name='shown',
        ),
        migrations.AlterField(
            model_name='markstyle',
            name='kind',
            field=models.CharField(choices=[('holiday', '공휴일'), ('term', '절기')], max_length=16),
        ),
        migrations.AlterField(
            model_name='specialday',
            name='kind',
            field=models.CharField(choices=[('holiday', '공휴일'), ('term', '절기')], help_text='공휴일·절기', max_length=16),
        ),
    ]
